# Generated by Django 4.2.6 on 2023-10-21 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=150)),
                ('slug_link', models.CharField(max_length=150, unique=True)),
                ('amount', models.IntegerField()),
                ('SAR_link', models.URLField(max_length=500)),
                ('AED_link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('باروكة شعر طبيعى', 'باروكة شعر طبيعى')], max_length=150)),
                ('wig_type', models.CharField(choices=[('جذور امامية', 'جذور امامية'), ('جذور كامله', 'جذور كامله'), ('جذور دائرية 360', 'جذور دائرية 360')], max_length=150)),
                ('wig_long', models.CharField(choices=[('12 Inch', '12 Inch'), ('14 Inch', '14 Inch'), ('16 Inch', '16 Inch'), ('18 Inch', '18 Inch'), ('20 Inch', '20 Inch'), ('22 Inch', '22 Inch'), ('24 Inch', '24 Inch'), ('26 Inch', '26 Inch'), ('28 Inch', '28 Inch'), ('30 Inch', '30 Inch'), ('32 Inch', '32 Inch'), ('34 Inch', '34 Inch'), ('36 Inch', '36 Inch'), ('38 Inch', '38 Inch'), ('40 Inch', '40 Inch')], max_length=150)),
                ('scalp_type', models.CharField(choices=[('دانتيل', 'دانتيل'), ('حرير', 'حرير')], max_length=150)),
                ('wig_color', models.CharField(choices=[('أسود طبيعى', 'أسود طبيعى'), ('بنى داكن', 'بنى داكن'), ('بنى فاتح', 'بنى فاتح'), ('اشقر', 'اشقر'), ('مخصل', 'مخصل')], max_length=150)),
                ('density', models.CharField(choices=[('130', '130'), ('150', '150'), ('200', '200'), ('250', '250')], max_length=150)),
                ('price', models.IntegerField(default=1500, validators=[django.core.validators.MaxValueValidator(7000), django.core.validators.MinValueValidator(400)])),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
