# Generated by Django 4.2.6 on 2023-11-22 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_phones2_alter_bill2_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phones2',
            new_name='Phone',
        ),
        migrations.AlterField(
            model_name='bill2',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 26, 13, 129108, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 26, 13, 127458, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 26, 13, 127458, tzinfo=datetime.timezone.utc)),
        ),
    ]
