# Generated by Django 4.2.6 on 2023-11-22 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_phones2_phone_alter_bill2_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill2',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 29, 35, 600738, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 29, 35, 596309, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 29, 35, 596309, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone',
            field=models.CharField(choices=[('5566525555', '5566525555'), ('968585852', '968585852'), ('60606060606060', '60606060606060')], max_length=31),
        ),
    ]
