# Generated by Django 4.2.6 on 2023-10-22 12:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('باروكة شعر طبيعى', 'باروكة شعر طبيعى')], max_length=150)),
                ('wig_type', models.CharField(choices=[('اختر نوع الباروكة', 'اختر نوع الباروكة'), ('جذور امامية', 'جذور امامية'), ('جذور كامله', 'جذور كامله'), ('جذور دائرية 360', 'جذور دائرية 360')], max_length=150)),
                ('wig_long', models.CharField(choices=[('طول الباروكة', 'طول الباروكة'), ('12 Inch', '12 Inch'), ('14 Inch', '14 Inch'), ('16 Inch', '16 Inch'), ('18 Inch', '18 Inch'), ('20 Inch', '20 Inch'), ('22 Inch', '22 Inch'), ('24 Inch', '24 Inch'), ('26 Inch', '26 Inch'), ('28 Inch', '28 Inch'), ('30 Inch', '30 Inch'), ('32 Inch', '32 Inch'), ('34 Inch', '34 Inch'), ('36 Inch', '36 Inch'), ('38 Inch', '38 Inch'), ('40 Inch', '40 Inch')], max_length=150)),
                ('scalp_type', models.CharField(choices=[('اختر نوع الفروة', 'اختر نوع الفروة'), ('دانتيل', 'دانتيل'), ('حرير', 'حرير')], max_length=150)),
                ('wig_color', models.CharField(choices=[('اختر لون الباروكة', 'اختر لون الباروكة'), ('أسود طبيعى', 'أسود طبيعى'), ('بنى داكن', 'بنى داكن'), ('بنى فاتح', 'بنى فاتح'), ('اشقر', 'اشقر'), ('مخصل', 'مخصل')], max_length=150)),
                ('density', models.CharField(choices=[('اختر كثافة الباروكة', 'اختر كثافة الباروكة'), ('130', '130'), ('150', '150'), ('200', '200'), ('250', '250')], max_length=150)),
                ('price', models.IntegerField(default=1500, validators=[django.core.validators.MaxValueValidator(7000), django.core.validators.MinValueValidator(400)])),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='density',
            field=models.CharField(choices=[('اختر كثافة الباروكة', 'اختر كثافة الباروكة'), ('130', '130'), ('150', '150'), ('200', '200'), ('250', '250')], max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='scalp_type',
            field=models.CharField(choices=[('اختر نوع الفروة', 'اختر نوع الفروة'), ('دانتيل', 'دانتيل'), ('حرير', 'حرير')], max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='wig_color',
            field=models.CharField(choices=[('اختر لون الباروكة', 'اختر لون الباروكة'), ('أسود طبيعى', 'أسود طبيعى'), ('بنى داكن', 'بنى داكن'), ('بنى فاتح', 'بنى فاتح'), ('اشقر', 'اشقر'), ('مخصل', 'مخصل')], max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='wig_long',
            field=models.CharField(choices=[('طول الباروكة', 'طول الباروكة'), ('12 Inch', '12 Inch'), ('14 Inch', '14 Inch'), ('16 Inch', '16 Inch'), ('18 Inch', '18 Inch'), ('20 Inch', '20 Inch'), ('22 Inch', '22 Inch'), ('24 Inch', '24 Inch'), ('26 Inch', '26 Inch'), ('28 Inch', '28 Inch'), ('30 Inch', '30 Inch'), ('32 Inch', '32 Inch'), ('34 Inch', '34 Inch'), ('36 Inch', '36 Inch'), ('38 Inch', '38 Inch'), ('40 Inch', '40 Inch')], max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='wig_type',
            field=models.CharField(choices=[('اختر نوع الباروكة', 'اختر نوع الباروكة'), ('جذور امامية', 'جذور امامية'), ('جذور كامله', 'جذور كامله'), ('جذور دائرية 360', 'جذور دائرية 360')], max_length=150),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('done_ordered_time', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.billingaddress')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coupon')),
                ('items', models.ManyToManyField(to='core.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
