# Generated by Django 4.2.6 on 2023-11-22 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bill2_date_alter_order_done_ordered_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.AlterField(
            model_name='addlink',
            name='link_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='addlink',
            name='slug_link',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='bill2',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 46, 6, 746648, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 46, 6, 744978, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 12, 46, 6, 744978, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone',
            field=models.CharField(choices=[('5555555555', '5555555555'), ('4444444444444', '4444444444444'), ('222222222222', '222222222222'), ('111111111', '111111111'), ('33333333333333333', '33333333333333333'), ('666666666666666', '666666666666666'), ('777777777777777', '777777777777777')], max_length=31),
        ),
    ]
