# Generated by Django 4.2.6 on 2023-10-28 12:17

import datetime
from django.db import migrations, models
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_order_done_ordered_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='zip',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(default='Egypt', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 12, 17, 28, 216843, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='pieces_num',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 12, 17, 28, 169971, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 12, 17, 28, 169971, tzinfo=datetime.timezone.utc)),
        ),
    ]
