# Generated by Django 4.2.6 on 2023-10-28 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_billingaddress_zip_billingaddress_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 12, 22, 28, 713741, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='pieces_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 12, 22, 28, 713741, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 12, 22, 28, 713741, tzinfo=datetime.timezone.utc)),
        ),
    ]
