# Generated by Django 4.2.6 on 2023-10-29 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_bill_date_alter_order_done_ordered_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='phone',
            new_name='customer_phone',
        ),
        migrations.AddField(
            model_name='bill',
            name='seller_phone_number',
            field=models.ForeignKey(default='2222', on_delete=django.db.models.deletion.CASCADE, to='core.phonenumber'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 13, 33, 45, 748956, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 13, 33, 45, 748956, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 13, 33, 45, 748956, tzinfo=datetime.timezone.utc)),
        ),
    ]
