# Generated by Django 4.2.6 on 2023-10-30 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_phone_bill_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 14, 57, 8, 941089, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bill',
            name='seller_phone_number',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 14, 57, 8, 936823, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 14, 57, 8, 936823, tzinfo=datetime.timezone.utc)),
        ),
    ]
