# Generated by Django 4.2.6 on 2023-10-31 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_bill_date_alter_order_done_ordered_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 9, 34, 11, 984130, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bill',
            name='seller_phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.phonenumber'),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 9, 34, 11, 982135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 9, 34, 11, 982135, tzinfo=datetime.timezone.utc)),
        ),
    ]
