# Generated by Django 4.2.6 on 2023-10-31 13:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0030_remove_account_phone_number_alter_billl_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 13, 28, 38, 119413, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 13, 28, 38, 117422, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 13, 28, 38, 116419, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Accounttt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('account_link', models.URLField(max_length=1000)),
                ('phone_number', models.CharField(blank=True, max_length=31, null=True)),
                ('marketer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
