# Generated by Django 4.2.6 on 2023-10-31 13:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0033_alter_billl_date_alter_order_done_ordered_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='f1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pho', models.CharField(max_length=31)),
            ],
        ),
        migrations.AlterField(
            model_name='billl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 13, 39, 44, 646053, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 13, 39, 44, 644061, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 13, 39, 44, 644061, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='f2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=1000)),
                ('man', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.f1')),
            ],
        ),
    ]
