# Generated by Django 4.2.6 on 2023-11-07 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_bill2_customer_name_alter_bill2_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=31)),
            ],
        ),
        migrations.AlterField(
            model_name='bill2',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 11, 6, 18, 676642, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bill2',
            name='wig_long',
            field=models.CharField(choices=[('طول الباروكة', 'طول الباروكة'), ('انش12', 'انش12'), ('انش14', 'انش14'), ('انش16', 'انش16'), ('انش18', 'انش18'), ('انش20', 'انش20'), ('انش22', 'انش22'), ('انش24', 'انش24'), ('انش26', 'انش26'), ('انش28', 'انش28'), ('انش30', 'انش30'), ('انش32', 'انش32'), ('انش34', 'انش34'), ('انش36', 'انش36'), ('انش38', 'انش38'), ('انش40', 'انش40')], max_length=150),
        ),
        migrations.AlterField(
            model_name='item',
            name='wig_long',
            field=models.CharField(choices=[('طول الباروكة', 'طول الباروكة'), ('انش12', 'انش12'), ('انش14', 'انش14'), ('انش16', 'انش16'), ('انش18', 'انش18'), ('انش20', 'انش20'), ('انش22', 'انش22'), ('انش24', 'انش24'), ('انش26', 'انش26'), ('انش28', 'انش28'), ('انش30', 'انش30'), ('انش32', 'انش32'), ('انش34', 'انش34'), ('انش36', 'انش36'), ('انش38', 'انش38'), ('انش40', 'انش40')], max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 11, 6, 18, 676642, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 11, 6, 18, 676642, tzinfo=datetime.timezone.utc)),
        ),
    ]
