# Generated by Django 4.2.6 on 2023-11-08 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_bill2_date_alter_order_done_ordered_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill2',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 13, 41, 48, 559564, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 13, 41, 48, 555016, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 13, 41, 48, 555016, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone',
            field=models.CharField(choices=[('5555555555', '5555555555'), ('4444444444444', '4444444444444'), ('222222222222', '222222222222'), ('111111111', '111111111'), ('445455', '445455'), ('64524242', '64524242'), ('427341757171', '427341757171')], max_length=31),
        ),
    ]
