# Generated by Django 4.2.6 on 2023-11-20 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_bill2_date_alter_order_done_ordered_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penality',
            name='slug_link',
            field=models.SlugField(default='111sdfsdfsdfsf525'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill2',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 11, 32, 41, 826865, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 11, 32, 41, 826865, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 11, 32, 41, 826865, tzinfo=datetime.timezone.utc)),
        ),
    ]
