# Generated by Django 4.2.6 on 2023-11-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_phone_alter_addlink_link_name_and_more'),
        ('core', '0062_penality_slug_link_alter_bill2_date_and_more'),
    ]

    operations = [
    ]
