# Generated by Django 4.2.6 on 2023-11-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_bill2_date_alter_order_done_ordered_time_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.phones'),
            preserve_default=False,
        ),
    ]
