# Generated by Django 4.2.6 on 2023-11-08 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_bill2_date_alter_order_done_ordered_time_and_more'),
        ('accounts', '0003_alter_profile_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.phones', unique=True),
        ),
    ]
