# Generated by Django 4.2.6 on 2023-11-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_pp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ph',
            field=models.CharField(choices=[('5555555555', '5555555555'), ('4444444444444', '4444444444444'), ('222222222222', '222222222222')], default=1, max_length=31),
            preserve_default=False,
        ),
    ]
