# Generated by Django 4.2.6 on 2023-11-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_ph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ph',
        ),
    ]
