# Generated by Django 4.2.6 on 2023-11-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_phone'),
        ('accounts', '0008_remove_profile_pp'),
    ]

    operations = [
    ]
